openapi: 3.0.3
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
tags:
- name: wait-list-order-controller
  description: Wait List Order Controller
- name: web-mvc-links-handler
  description: Web Mvc Links Handler
- name: operation-handler
  description: Operation Handler
- name: basic-error-controller
  description: Basic Error Controller
- name: ts-wait-order-service
  description: Service name
paths:
  /actuator:
    get:
      tags: [web-mvc-links-handler, ts-wait-order-service]
      summary: links
      operationId: linksUsingGET
      responses:
        '200':
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/Map_string_Link_'
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/Map_string_Link_'
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/Map_string_Link_'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-service-name: ts-wait-order-service
  /actuator/health:
    get:
      tags: [operation-handler, ts-wait-order-service]
      summary: handle
      operationId: handleUsingGET_1
      requestBody:
        $ref: '#/components/requestBodies/handleUsingGET_1Body'
      responses:
        '200':
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-service-name: ts-wait-order-service
  /actuator/health/**:
    get:
      tags: [operation-handler, ts-wait-order-service]
      summary: handle
      operationId: handleUsingGET
      requestBody:
        $ref: '#/components/requestBodies/handleUsingGET_1Body'
      responses:
        '200':
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-service-name: ts-wait-order-service
  /actuator/info:
    get:
      tags: [operation-handler, ts-wait-order-service]
      summary: handle
      operationId: handleUsingGET_2
      requestBody:
        $ref: '#/components/requestBodies/handleUsingGET_1Body'
      responses:
        '200':
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-service-name: ts-wait-order-service
  /api/v1/waitorderservice/order:
    post:
      tags: [wait-list-order-controller, ts-wait-order-service]
      summary: createNewOrder
      operationId: createNewOrderUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WaitListOrderVO'
        description: createOrder
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HttpEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-service-name: ts-wait-order-service
  /api/v1/waitorderservice/orders:
    get:
      tags: [wait-list-order-controller, ts-wait-order-service]
      summary: getAllOrders
      operationId: getAllOrdersUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HttpEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-service-name: ts-wait-order-service
  /api/v1/waitorderservice/waitlistorders:
    get:
      tags: [wait-list-order-controller, ts-wait-order-service]
      summary: getWaitListOrders
      operationId: getWaitListOrdersUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HttpEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-service-name: ts-wait-order-service
  /api/v1/waitorderservice/welcome:
    get:
      tags: [wait-list-order-controller, ts-wait-order-service]
      summary: home
      operationId: homeUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-service-name: ts-wait-order-service
  /error:
    get:
      tags: [basic-error-controller, ts-wait-order-service]
      summary: error
      operationId: errorUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-service-name: ts-wait-order-service
    head:
      tags: [basic-error-controller, ts-wait-order-service]
      summary: error
      operationId: errorUsingHEAD
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      x-service-name: ts-wait-order-service
    post:
      tags: [basic-error-controller, ts-wait-order-service]
      summary: error
      operationId: errorUsingPOST
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-service-name: ts-wait-order-service
    put:
      tags: [basic-error-controller, ts-wait-order-service]
      summary: error
      operationId: errorUsingPUT
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-service-name: ts-wait-order-service
    delete:
      tags: [basic-error-controller, ts-wait-order-service]
      summary: error
      operationId: errorUsingDELETE
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      x-service-name: ts-wait-order-service
    options:
      tags: [basic-error-controller, ts-wait-order-service]
      summary: error
      operationId: errorUsingOPTIONS
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      x-service-name: ts-wait-order-service
    patch:
      tags: [basic-error-controller, ts-wait-order-service]
      summary: error
      operationId: errorUsingPATCH
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      x-service-name: ts-wait-order-service
servers:
- url: //129.62.148.112:32744
components:
  requestBodies:
    handleUsingGET_1Body:
      content:
        application/json:
          schema:
            type: object
            additionalProperties:
              type: string
      description: body
  schemas:
    WaitListOrderVO:
      type: object
      properties:
        accountId:
          type: string
        contactsId:
          type: string
        date:
          type: string
          format: date-time
        from:
          type: string
        price:
          type: string
        seatType:
          type: integer
          format: int32
        to:
          type: string
        tripId:
          type: string
    HttpEntity:
      type: object
      properties:
        body:
          type: object
    ModelAndView:
      type: object
      properties:
        empty:
          type: boolean
        model:
          type: object
        modelMap:
          type: object
          additionalProperties:
            type: object
        reference:
          type: boolean
        status:
          type: string
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        view:
          $ref: '#/components/schemas/View'
        viewName:
          type: string
    View:
      type: object
      properties:
        contentType:
          type: string
    Link:
      type: object
      properties:
        href:
          type: string
        templated:
          type: boolean
    Map_string_Link_:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Link' 